package com.haitaos.finallbbs.model;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.parent_id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.file_url
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.file_name
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.parent_id
     *
     * @return the value of project.parent_id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.parent_id
     *
     * @param parentId the value for project.parent_id
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.file_url
     *
     * @return the value of project.file_url
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.file_url
     *
     * @param fileUrl the value for project.file_url
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.file_name
     *
     * @return the value of project.file_name
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.file_name
     *
     * @param fileName the value for project.file_name
     *
     * @mbg.generated Mon Apr 26 22:07:54 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}